language: node_js
node_js:
- 7.3.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - xvfb
    - libgnome-keyring-dev
env: CXX=g++-4.8
before_install: npm install -g grunt-cli
services: mongodb
deploy:
  provider: heroku
  app: hanno-oskar
  api_key:
    secure: #
